# Cadastra uma nova receita
POST http://localhost:8080/receitas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJlbXByZXNhSWQiOjEsImV4cCI6MTYzMDEwOTUxOSwidXN1YXJpb0lkIjoxfQ.lH_gd8pB6_-2DfZ9uO2tDdgbLv3eReE695JKTSyRSFI

{
    "descricao"     : "Bolo",
    "modoPreparo"   : "Teste preparo Bolo",
    "categoria"     : 5,
    "rendimento"    : 5,
    "tempoPreparo"  : 90,
    "preco"         : 80.50,
    "precoSugerido" : 70.30,
    "ingredientes" : [
        {
            "ingredienteId" : 1,
            "unidadeMedida" : "g",
            "quantidade"    : 150
        },
        {
            "ingredienteId" : 2,
            "unidadeMedida" : "ml",
            "quantidade"    : 200
        }
    ],
    "utensilios" : [
    	{
            "utensilioId" : 1
    	},
    	{
            "utensilioId" : 2
    	}
    ]
}
###

# Busca todas as receitas
GET http://localhost:8080/receitas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJlbXByZXNhSWQiOjEsImV4cCI6MTYzMDEwOTUxOSwidXN1YXJpb0lkIjoxfQ.lH_gd8pB6_-2DfZ9uO2tDdgbLv3eReE695JKTSyRSFI
###

# Busca uma receita pelo ID
GET http://localhost:8080/receitas/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJlbXByZXNhSWQiOjEsImV4cCI6MTYzMDEwOTUxOSwidXN1YXJpb0lkIjoxfQ.lH_gd8pB6_-2DfZ9uO2tDdgbLv3eReE695JKTSyRSFI
###

# Busca as receita de acordo com os parâmetros
GET http://localhost:8080/receitas?categoria=5&descricao=Bolo&usuarioId=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJlbXByZXNhSWQiOjEsImV4cCI6MTYzMDEwOTUxOSwidXN1YXJpb0lkIjoxfQ.lH_gd8pB6_-2DfZ9uO2tDdgbLv3eReE695JKTSyRSFI
###

# Atualiza nova receita
PUT http://localhost:8080/receitas/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJlbXByZXNhSWQiOjEsImV4cCI6MTYzMDEwOTUxOSwidXN1YXJpb0lkIjoxfQ.lH_gd8pB6_-2DfZ9uO2tDdgbLv3eReE695JKTSyRSFI

{
    "descricao"     : "Bolo Prestigio",
    "modoPreparo"   : "Teste preparo Bolo",
    "categoria"     : 5,
    "rendimento"    : 5,
    "tempoPreparo"  : 90,
    "preco"         : 80.50,
    "precoSugerido" : 70.30,
    "ingredientes" : [
        {
            "ingredienteId" : 1,
            "unidadeMedida" : "g",
            "quantidade"    : 150
        },
        {
            "ingredienteId" : 2,
            "unidadeMedida" : "ml",
            "quantidade"    : 200
        }
    ],
    "utensilios" : [
    	{
            "utensilioId" : 1
    	},
    	{
            "utensilioId" : 2
    	}
    ]
}
###